### ISSUE TITLE
Stats Page

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/osw-hacktoberfest-2019#10]
- [ ]  Color picked mostly
- [x] Avg color (from _rgba_ values)
- [x] Number of commits of each day of the week grouped by hours
- [x] ?

**Comment by baumannzone** [comment]
@all-contributors please add @CodingCarlos for examples, ideas

**Comment by DanielOrmeno** [comment]
Hello, I'd like to work on this, I'll work on a PR soon.

**Comment by baumannzone** [comment]
> Hello, I'd like to work on this, I'll work on a PR soon.

What features do you have in mind?

**Comment by DanielOrmeno** [comment]
I'm starting with Number of contributors and Average Color (resulting from averaging the R, G, and B value of colors submitted by contributors).

I'll see what else I can add :D

**Comment by DanielOrmeno** [comment]
Im also thinking of creating a grid of all the colors used, I'll have a play with this to see if it looks cool

**Comment by baumannzone** [comment]
If you don't mind, share progress of what you doing here (images are ok, you can paste it from the clipboard) because I'm doing some charts too 🤓

**Comment by DanielOrmeno** [comment]
Sure! Heres a screenshot with the current data:

<img width="1249" alt="Screen Shot 2019-10-02 at 2 38 18 pm" src="https://user-images.githubusercontent.com/7246206/66084074-9ef4c180-e522-11e9-8acb-a2772ae64a13.png">

And here's one with some mock data to test responsiveness:
<img width="1180" alt="Screen Shot 2019-10-02 at 2 53 52 pm" src="https://user-images.githubusercontent.com/7246206/66084857-7ec60200-e524-11e9-8d85-838c95adef98.png">

**Comment by DanielOrmeno** [comment]
Submitted [PR 37](https://github.com/OSWeekends/osw-hacktoberfest-2019/pull/37)

**Comment by baumannzone** [comment]
Done!

Ref #34 . Feel free to add anything you think it's useful or funny. I'm playing with the github api to make some funny charts 💃

**Comment by DanielOrmeno** [comment]
Great! Thank you for the merge.
