### ISSUE TITLE
CSS fun animations on mouse over

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/osw-hacktoberfest-2019#11]
For each user-card

**Comment by baumannzone** [comment]
@all-contributors please add @baumannzone for code examples content infra

**Comment by DanielOrmeno** [comment]
Hi! I'd like to work on this, I want to implement random animations when hovering each card!

**Comment by DanielOrmeno** [comment]
![PR3](https://user-images.githubusercontent.com/7246206/66274846-6cefa200-e837-11e9-9233-e6b7d5fcab5a.gif)
