### ISSUE TITLE
Replace API Rest endpoints with GraphQL

### ISSUE THREAD

**Issue by smorcuend** [OSWeekends/osw-hacktoberfest-2019#196]
The current mechanism for retrieve stats from server uses Github API v3 (REST Api)

I propose to use Github API v4 (GraphQL) as technology to retrieve data from server.
https://developer.github.com/v4/

The main limitation references to set permissions to retrieve some information from organization and repositories.

More info about querying: 
 - Query syntax: https://gist.github.com/smorcuend/31975e48a9dbd68dedf3510608a87130
- Apollo Vue: https://github.com/Akryum/vue-apollo

**Comment by baumannzone** [comment]
Are you going to do it?

**Comment by smorcuend** [comment]
Sure! 
We will ask you about read permissions policy for this repository
