### ISSUE TITLE
Location null in GenerateJson

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/osw-hacktoberfest-2019#200]
Generate Page:
![image](https://user-images.githubusercontent.com/5422102/66397359-ee803500-e9db-11e9-9ed2-c00258a3c94b.png)

Sometimes, location's response is `null` when asking for the user data in github.

### Do:
Transform the response shown in the result box.  
Change `"location": null` by `"location": ""` (empty string)

**Comment by Alig1493** [comment]
I'm new to learning Vue.js and I'd like to take this up.

**Comment by baumannzone** [comment]
Do it, it's really easy :D 

If you need help, ask here 💙

**Comment by Alig1493** [comment]
Hello. I tried to set up the project but I get an error for this command: `vue-cli-service serve`
I installed the vue dependencies using [this](https://cli.vuejs.org/guide/installation.html)
The full traceback for the error is this:
```
> osw-hacktoberfest-2019@0.1.0 serve /home/ali/work_stash/osw-hacktoberfest-2019
> vue-cli-service serve

sh: 1: vue-cli-service: not found

npm ERR! Linux 5.0.0-29-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! osw-hacktoberfest-2019@0.1.0 serve: `vue-cli-service serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the osw-hacktoberfest-2019@0.1.0 serve script 'vue-cli-service serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osw-hacktoberfest-2019 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osw-hacktoberfest-2019
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osw-hacktoberfest-2019
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ali/work_stash/osw-hacktoberfest-2019/npm-debug.log

```

Thank You.

**Comment by CodingCarlos** [comment]
Maybe is too obvious, but just to make sure:

Have you executed `npm install`?

**Comment by smorcuend** [comment]
All Github data on this repository can be replaced by ApiV4 with GraphQL and apollo-Vue. Problems with initialization and caching are resolved with this library

**Comment by Alig1493** [comment]
I added the change for handling default location null value as empty string here: [#219](https://github.com/OSWeekends/osw-hacktoberfest-2019/pull/219)
