### ISSUE TITLE
Funny list of Releases' name

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/osw-hacktoberfest-2019#85]
Examples: 

- Chomped a Lion
- Aithne Brazensnow
- Lugosi Devilstein
- Misty Ghostbreath

I like funny or useless names 🎃 💃

**Comment by DeadReBorn** [comment]
- Boo
- Hack O’Lantern
- Donald Trumpkin lol

 🎃 🎃 🎃 🎃 🎃 🎃 🎃 🎃

**Comment by joamarderije** [comment]
Hi how can i contribute here ?
