### ISSUE TITLE
Share on twitter

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/osw-hacktoberfest-2019#9]
Create a link to share on twitter with default text

**Comment by Agusnez** [comment]
Challenge accepted!

**Comment by Agusnez** [comment]
Pull request made to `develop` branch! #26

**Comment by baumannzone** [comment]
Wow, nice job @Agusnez !

I already accepted your PR, but can you put the button down (after the result block) and change text to "Share on twitter"?

Thank you!
> You may open another PR

**Comment by baumannzone** [comment]
please @all-contributors add @Agusnez for code

**Comment by baumannzone** [comment]
Did you know that @Agusnez ? I can't tweet. I don't know why 🤔 

![image](https://user-images.githubusercontent.com/5422102/66023874-bfa52300-e4f2-11e9-968e-d6bb7d401a2c.png)

**Comment by Agusnez** [comment]
I couldn't reproduce the error @baumannzone. Maybe your Twitter session was expired? I tried in desktop and mobile with two different accounts and it allowed me to tweet without problems 😕

![Screenshot_20191002_090437](https://user-images.githubusercontent.com/15832553/66024569-748c0f80-e4f4-11e9-8b3f-f1a9789f96e7.jpg)

**Comment by baumannzone** [comment]
I need to read the docs of share apis. Looks like it's using your session or something

**Comment by Agusnez** [comment]
@baumannzone I have read that Twitter is [malfunctioning](https://api.twitterstat.us/). Please, try again after a few hours.

**Comment by Agusnez** [comment]
> Wow, nice job @Agusnez !
> 
> I already accepted your PR, but can you put the button down (after the result block) and change text to "Share on twitter"?
> 
> Thank you!
> 
> > You may open another PR

Yeah, sure! I will work on it whenever I have time today! 👍

**Comment by baumannzone** [comment]
> @baumannzone I have read that Twitter is [malfunctioning](https://api.twitterstat.us/). Please, try again after a few hours.

Looks like it's working now:
![image](https://user-images.githubusercontent.com/5422102/66033835-5a5c2c80-e508-11e9-9952-6d3746cb77df.png)
